import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Provider, useDispatch, useSelector } from 'react-redux';
import { BrowserRouter, Link, Navigate, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { api, json, store, setUser, signedIn, signedOut } from './store';
import './style.css';

const formatDate = date => date ? new Date(date).toLocaleDateString(undefined, { month: 'short', year: 'numeric' }) : 'Present';
const initials = name => (name || '?').split(' ').map(x => x[0]).slice(0, 2).join('').toUpperCase();
function useSession() { return useSelector(s => s.session); }
function useRequest() {
  const { token } = useSession(); const [error, setError] = useState('');
  const run = async (path, options) => { setError(''); try { return await api(path, { ...options, token }); } catch (e) { setError(e.message); throw e; } };
  return { run, error, setError };
}
function ErrorText({ error }) { return error ? <div className="error" role="alert">{error}</div> : null; }
function Header() {
  const { user } = useSession(); const dispatch = useDispatch();
  return <header className="header"><div className="header-inner"><Link to="/" className="brand"><span className="brand-icon">&lt;/&gt;</span> developer<span>connect</span></Link><nav><NavLink to="/developers">Explore</NavLink><NavLink to="/feed">Community</NavLink>{user ? <><NavLink to="/dashboard">Dashboard</NavLink><button className="nav-button" onClick={() => dispatch(signedOut())}>Sign out</button></> : <><NavLink to="/login">Sign in</NavLink><Link className="nav-join" to="/register">Join now <span>↗</span></Link></>}</nav></div></header>;
}
function Footer() { return <footer className="footer">Developer Connect <span>·</span> A place to build, share, and grow together.</footer>; }
function Layout({ children }) { return <><Header/>{children}<Footer/></>; }
function Protected({ children }) { const { token } = useSession(); return token ? children : <Navigate to="/login" replace/>; }
function Hero() {
  return <main><section className="hero"><div className="hero-content"><span className="eyebrow"><span className="green-dot"/> THE DEVELOPER COMMUNITY</span><h1>Great things are<br/>built <em>together.</em></h1><p>Find your people. Share what you're building. Make connections that move your career forward.</p><div className="hero-actions"><Link className="button primary" to="/register">Join the community <span>↗</span></Link><Link className="button ghost" to="/developers">Explore developers <span>→</span></Link></div><div className="hero-proof"><span className="avatar-stack"><b>AC</b><b>JD</b><b>MK</b></span><span>Build your profile. Find your community.</span></div></div><div className="hero-art" aria-hidden="true"><div className="art-grid"/><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-card card-code"><div className="card-dots">● ● ●</div><code><i>const</i> future = <strong>await</strong> buildTogether();<br/><span>// Your next connection starts here</span></code></div><div className="art-card card-profile"><div className="mini-avatar">DC</div><div><strong>Your network, growing.</strong><small>Build. Connect. Create.</small></div><span className="status-dot"/></div><div className="art-spark">✳</div></div></section><section className="feature-wrap"><div className="section-heading"><span className="eyebrow dark">BUILT FOR THE BUILDER IN YOU</span><h2>More than a profile.<br/><em>A place to belong.</em></h2></div><div className="features"><article><span className="feature-icon">01 /</span><h3>Show your work</h3><p>Bring your skills, experience, education, and links together in one developer profile.</p></article><article><span className="feature-icon">02 /</span><h3>Find your people</h3><p>Explore the community and discover developers with similar interests and skills.</p></article><article><span className="feature-icon">03 /</span><h3>Join the conversation</h3><p>Share updates, leave a comment, and support the work your peers are doing.</p></article></div></section><section className="cta"><div><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2>Make your mark<br/>on the community.</h2></div><Link className="button light" to="/register">Create your profile ↗</Link></section></main>;
}
function Auth({ mode }) {
  const dispatch = useDispatch(), navigate = useNavigate(); const { run, error } = useRequest();
  const [form, setForm] = useState({ name: '', email: '', password: '' }); const [busy, setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); setBusy(true); try { const data = await run(`/auth/${mode}`, { method: 'POST', body: json(mode === 'login' ? { email: form.email, password: form.password } : form) }); dispatch(signedIn(data)); navigate('/dashboard'); } catch {} finally { setBusy(false); } };
  return <main className="auth-wrap"><div className="auth-aside"><span className="eyebrow">YOUR COMMUNITY AWAITS</span><h1>Find your next<br/><em>connection.</em></h1><p>Good work starts with good people. You're in the right place.</p><div className="aside-mark">&lt;/&gt;</div></div><div className="auth-panel"><div className="form-card"><span className="eyebrow dark">{mode === 'login' ? 'WELCOME BACK' : 'GET STARTED'}</span><h2>{mode === 'login' ? 'Sign in to your account' : 'Join Developer Connect'}</h2><p>{mode === 'login' ? 'Pick up where you left off.' : 'Create your account and start connecting.'}</p><form onSubmit={submit}><ErrorText error={error}/>{mode === 'register' && <label>Full name<input required maxLength="80" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name"/></label>}<label>Email address<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com"/></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="At least 8 characters"/></label><button disabled={busy} className="button primary full">{busy ? 'Please wait…' : mode === 'login' ? 'Sign in →' : 'Create account →'}</button></form><p className="auth-switch">{mode === 'login' ? <>New here? <Link to="/register">Create an account</Link></> : <>Already a member? <Link to="/login">Sign in</Link></>}</p></div></div></main>;
}
function PageHeader({ eyebrow, title, description, action }) { return <div className="page-head"><div><span className="eyebrow dark">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function Avatar({ name, large = false }) { return <span className={`avatar ${large ? 'large' : ''}`}>{initials(name)}</span>; }
function Developers() {
  const [profiles, setProfiles] = useState([]), [search, setSearch] = useState(''), [error, setError] = useState('');
  useEffect(() => { api('/profiles').then(setProfiles).catch(e => setError(e.message)); }, []);
  const filtered = profiles.filter(p => `${p.user?.name} ${p.headline} ${p.location} ${p.skills.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  return <main className="container"><PageHeader eyebrow="THE COMMUNITY" title="Meet the developers." description="Discover the people making things happen."/><div className="search-line"><input aria-label="Search developers" placeholder="Search names, skills, or locations..." value={search} onChange={e => setSearch(e.target.value)}/><span>{filtered.length} developers</span></div><ErrorText error={error}/><div className="developer-grid">{filtered.map(p => <Link className="developer-card" key={p._id} to={`/developers/${p.handle}`}><Avatar name={p.user?.name}/><h3>{p.user?.name}</h3><p>{p.headline}</p><small>{p.location || 'Location not listed'}</small><div className="chips">{p.skills.slice(0, 4).map(s => <span key={s}>{s}</span>)}</div><span className="card-link">View profile ↗</span></Link>)}</div>{!filtered.length && !error && <div className="empty">No developers found. Try another search or be the first to <Link to="/register">join</Link>.</div>}</main>;
}
function Timeline({ entries, label }) { return entries?.length ? <section className="profile-section"><h2>{label}</h2>{entries.map(item => <div className="timeline-item" key={item._id}><div className="timeline-dot"/><div><h3>{item.title}</h3><strong>{item.organization}</strong><p>{formatDate(item.from)} – {item.current ? 'Present' : formatDate(item.to)}{item.location && ` · ${item.location}`}</p>{item.description && <p className="body-text">{item.description}</p>}</div></div>)}</section> : null; }
function Profile() {
  const { handle } = useParams(); const [profile, setProfile] = useState(null), [error, setError] = useState('');
  useEffect(() => { api(`/profiles/${encodeURIComponent(handle)}`).then(setProfile).catch(e => setError(e.message)); }, [handle]);
  if (error) return <main className="container"><ErrorText error={error}/></main>;
  if (!profile) return <main className="container"><p>Loading profile…</p></main>;
  return <main className="container profile-page"><Link to="/developers" className="back-link">← All developers</Link><div className="profile-banner"><div className="profile-banner-pattern"/><Avatar name={profile.user?.name} large/><h1>{profile.user?.name}</h1><p>{profile.headline}</p>{profile.location && <small>⌖ {profile.location}</small>}</div><div className="profile-layout"><div><section className="profile-section"><h2>About</h2><p className="body-text">{profile.bio || 'This developer has not added a bio yet.'}</p></section><Timeline entries={profile.experience} label="Experience"/><Timeline entries={profile.education} label="Education"/></div><aside className="profile-side"><h3>Skills & tools</h3><div className="chips">{profile.skills.map(s => <span key={s}>{s}</span>)}</div><h3>Elsewhere</h3>{Object.entries(profile.links || {}).filter(([,v]) => v).map(([k,v]) => <a key={k} href={v} target="_blank" rel="noopener noreferrer">{k} ↗</a>)}{profile.githubUsername && <a href={`https://github.com/${encodeURIComponent(profile.githubUsername)}`} target="_blank" rel="noopener noreferrer">GitHub profile ↗</a>}</aside></div></main>;
}
function Dashboard() {
  const { user, token } = useSession(); const [profile, setProfile] = useState(null), [error, setError] = useState('');
  useEffect(() => { api('/profiles/me', { token }).then(setProfile).catch(e => setError(e.message)); }, [token]);
  return <main className="container"><PageHeader eyebrow="YOUR SPACE" title={`Welcome back, ${user?.name?.split(' ')[0] || 'developer'}.`} description="Here's a snapshot of your developer presence." action={<Link className="button primary" to="/dashboard/edit">{profile ? 'Edit profile ↗' : 'Create profile ↗'}</Link>}/><ErrorText error={error}/>{profile ? <div className="dashboard-grid"><div className="dashboard-main"><div className="dashboard-card"><Avatar name={user?.name} large/><div><span className="eyebrow dark">YOUR PROFILE</span><h2>{profile.headline}</h2><p>{profile.bio || 'Add a bio to tell the community about yourself.'}</p><Link to={`/developers/${profile.handle}`}>View public profile ↗</Link></div></div><div className="stat-row"><div><strong>{profile.skills.length}</strong><span>Skills</span></div><div><strong>{profile.experience.length}</strong><span>Roles</span></div><div><strong>{profile.education.length}</strong><span>Education</span></div></div></div><div className="dashboard-tip"><span className="eyebrow dark">KEEP BUILDING</span><h3>Make a connection today.</h3><p>See what your peers are building and join the conversation.</p><Link className="button dark" to="/feed">Explore community →</Link></div></div> : <div className="empty welcome-empty"><span className="empty-icon">✳</span><h2>Let's get you set up.</h2><p>Create a profile so other developers can get to know you and your work.</p><Link className="button primary" to="/dashboard/edit">Create your profile →</Link></div>}</main>;
}
const blankProfile = { handle: '', headline: '', location: '', bio: '', skills: [], githubUsername: '', links: { website: '', github: '', linkedin: '', x: '' } };
function EditProfile() {
  const { token } = useSession(), navigate = useNavigate(); const { run, error, setError } = useRequest();
  const [form, setForm] = useState(blankProfile), [skills, setSkills] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { api('/profiles/me', { token }).then(p => { if (p) { setForm(p); setSkills(p.skills.join(', ')); } }).catch(e => setError(e.message)); }, [token]);
  const set = (key, value) => setForm(f => ({ ...f, [key]: value }));
  const submit = async e => { e.preventDefault(); setBusy(true); try { await run('/profiles/me', { method: 'PUT', body: json({ handle: form.handle, headline: form.headline, location: form.location || '', bio: form.bio || '', skills: skills.split(',').map(s => s.trim()).filter(Boolean), githubUsername: form.githubUsername || '', links: Object.fromEntries(['website','github','linkedin','x'].map(k => [k, form.links?.[k] || ''])) }) }); navigate('/dashboard'); } catch {} finally { setBusy(false); } };
  return <main className="container narrow"><Link to="/dashboard" className="back-link">← Dashboard</Link><PageHeader eyebrow="PROFILE SETTINGS" title="Tell your story." description="Show the community who you are and what you do."/><form className="editor" onSubmit={submit}><ErrorText error={error}/><div className="form-grid"><label>Profile handle *<input required pattern="[a-z0-9-]{3,30}" value={form.handle} onChange={e => set('handle', e.target.value.toLowerCase())} placeholder="your-name"/></label><label>Headline *<input required maxLength="120" value={form.headline} onChange={e => set('headline', e.target.value)} placeholder="Full-stack developer"/></label><label>Location<input value={form.location || ''} onChange={e => set('location', e.target.value)} placeholder="San Francisco, CA"/></label><label>GitHub username<input value={form.githubUsername || ''} onChange={e => set('githubUsername', e.target.value)} placeholder="username"/></label></div><label>About you<textarea rows="5" maxLength="1500" value={form.bio || ''} onChange={e => set('bio', e.target.value)} placeholder="What are you building? What excites you?"/></label><label>Skills <small>(comma separated)</small><input value={skills} onChange={e => setSkills(e.target.value)} placeholder="JavaScript, React, Node.js"/></label><h3>Your links</h3><div className="form-grid">{['website','github','linkedin','x'].map(k => <label key={k}>{k}<input type="url" value={form.links?.[k] || ''} onChange={e => setForm(f => ({ ...f, links: { ...f.links, [k]: e.target.value } }))} placeholder="https://..."/></label>)}</div><button disabled={busy} className="button primary">{busy ? 'Saving…' : 'Save profile →'}</button></form><EntryManager/></main>;
}
function EntryManager() {
  const { token } = useSession(); const [profile, setProfile] = useState(null), [kind, setKind] = useState('experience'), [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', organization: '', location: '', from: '', to: '', current: false, description: '' });
  useEffect(() => { api('/profiles/me', { token }).then(setProfile).catch(e => setError(e.message)); }, [token]);
  const submit = async e => { e.preventDefault(); setError(''); try { const updated = await api(`/profiles/me/${kind}`, { token, method: 'POST', body: json({ ...form, from: form.from, to: form.current || !form.to ? null : form.to }) }); setProfile(updated); setForm({ title: '', organization: '', location: '', from: '', to: '', current: false, description: '' }); } catch (e) { setError(e.message); } };
  const remove = async id => { try { const updated = await api(`/profiles/me/${kind}/${id}`, { token, method: 'DELETE' }); setProfile(updated); } catch(e) { setError(e.message); } };
  if (!profile) return null;
  return <section className="editor entries"><h2>Experience & education</h2><div className="tabs"><button className={kind === 'experience' ? 'selected' : ''} onClick={() => setKind('experience')}>Experience</button><button className={kind === 'education' ? 'selected' : ''} onClick={() => setKind('education')}>Education</button></div><ErrorText error={error}/>{profile[kind]?.map(item => <div className="entry-row" key={item._id}><span><strong>{item.title}</strong><small>{item.organization} · {formatDate(item.from)}</small></span><button onClick={() => remove(item._id)} aria-label={`Remove ${item.title}`}>Remove</button></div>)}<form onSubmit={submit}><h3>Add {kind}</h3><div className="form-grid"><label>{kind === 'experience' ? 'Job title' : 'Degree or program'} *<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/></label><label>{kind === 'experience' ? 'Company' : 'School'} *<input required value={form.organization} onChange={e => setForm({ ...form, organization: e.target.value })}/></label><label>Start date *<input required type="date" value={form.from} onChange={e => setForm({ ...form, from: e.target.value })}/></label><label>End date<input type="date" disabled={form.current} value={form.to} onChange={e => setForm({ ...form, to: e.target.value })}/></label></div><label className="check"><input type="checkbox" checked={form.current} onChange={e => setForm({ ...form, current: e.target.checked, to: e.target.checked ? '' : form.to })}/> Currently here</label><label>Location<input value={form.location} onChange={e => setForm({ ...form, location: e.target.value })}/></label><label>Description<textarea rows="3" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></label><button className="button dark">Add {kind} +</button></form></section>;
}
function Feed() {
  const { user, token } = useSession(); const [posts, setPosts] = useState([]), [page, setPage] = useState(1), [more, setMore] = useState(false), [draft, setDraft] = useState(''), [comments, setComments] = useState({}), [error, setError] = useState('');
  const load = async n => { try { const data = await api(`/posts?page=${n}`); setPosts(old => n === 1 ? data.posts : [...old, ...data.posts]); setMore(data.hasMore); setPage(n); } catch(e) { setError(e.message); } };
  useEffect(() => { load(1); }, []);
  const create = async e => { e.preventDefault(); try { await api('/posts', { token, method: 'POST', body: json({ text: draft }) }); setDraft(''); await load(1); } catch(e) { setError(e.message); } };
  const remove = async id => { try { await api(`/posts/${id}`, { token, method: 'DELETE' }); setPosts(old => old.filter(p => p._id !== id)); } catch(e) { setError(e.message); } };
  const like = async id => { try { const data = await api(`/posts/${id}/like`, { token, method: 'PUT' }); setPosts(old => old.map(p => p._id === id ? { ...p, likes: data.likes } : p)); } catch(e) { setError(e.message); } };
  const comment = async (e, id) => { e.preventDefault(); try { await api(`/posts/${id}/comments`, { token, method: 'POST', body: json({ text: comments[id] }) }); setComments({ ...comments, [id]: '' }); await load(1); } catch(e) { setError(e.message); } };
  const deleteComment = async (postId, id) => { try { await api(`/posts/${postId}/comments/${id}`, { token, method: 'DELETE' }); setPosts(old => old.map(p => p._id === postId ? { ...p, comments: p.comments.filter(c => c._id !== id) } : p)); } catch(e) { setError(e.message); } };
  return <main className="container feed-container"><PageHeader eyebrow="THE CONVERSATION" title="Community feed." description="Good ideas grow when we share them."/><ErrorText error={error}/>{user ? <form className="compose" onSubmit={create}><div className="compose-head"><Avatar name={user.name}/><strong>What are you working on?</strong></div><textarea required maxLength="2000" value={draft} onChange={e => setDraft(e.target.value)} placeholder="Share an update, a question, or a win with the community..." rows="3"/><div className="compose-foot"><span>Keep the conversation going.</span><button className="button primary">Share post ↗</button></div></form> : <div className="feed-prompt"><span>Have something to share?</span> <Link to="/login">Sign in to join the conversation →</Link></div>}{posts.map(post => <article className="post" key={post._id}><div className="post-head"><Avatar name={post.user?.name}/><div><strong>{post.user?.name || 'Developer'}</strong><small>{new Date(post.createdAt).toLocaleDateString()}</small></div>{user?._id === post.user?._id && <button className="text-button post-delete" onClick={() => remove(post._id)}>Delete</button>}</div><p className="post-text">{post.text}</p><div className="post-actions"><button disabled={!user} onClick={() => like(post._id)} className={post.likes.some(id => id === user?._id) ? 'liked' : ''}>♥ <span>{post.likes.length} likes</span></button><span>◌ {post.comments.length} comments</span></div>{post.comments.length > 0 && <div className="comments">{post.comments.map(c => <div className="comment" key={c._id}><Avatar name={c.user?.name}/><div><strong>{c.user?.name || 'Developer'}</strong><p>{c.text}</p></div>{(user?._id === c.user?._id || user?._id === post.user?._id) && <button className="text-button" onClick={() => deleteComment(post._id, c._id)}>Remove</button>}</div>)}</div>}{user && <form className="comment-form" onSubmit={e => comment(e, post._id)}><input required maxLength="2000" aria-label="Write a comment" placeholder="Write a comment..." value={comments[post._id] || ''} onChange={e => setComments({ ...comments, [post._id]: e.target.value })}/><button type="submit">Post →</button></form>}</article>)}{!posts.length && !error && <div className="empty">No posts yet. Start the conversation.</div>}{more && <button className="button ghost more" onClick={() => load(page + 1)}>Load more posts ↓</button>}</main>;
}
function App() {
  const { token } = useSession(); const dispatch = useDispatch();
  useEffect(() => { if (token) api('/auth/me', { token }).then(data => dispatch(setUser(data.user))).catch(() => dispatch(signedOut())); }, [token, dispatch]);
  return <Layout><Routes><Route path="/" element={<Hero/>}/><Route path="/login" element={<Auth mode="login"/>}/><Route path="/register" element={<Auth mode="register"/>}/><Route path="/developers" element={<Developers/>}/><Route path="/developers/:handle" element={<Profile/>}/><Route path="/feed" element={<Feed/>}/><Route path="/dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="/dashboard/edit" element={<Protected><EditProfile/></Protected>}/><Route path="*" element={<main className="container empty"><h1>Page not found</h1><Link to="/">Go home →</Link></main>}/></Routes></Layout>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><Provider store={store}><BrowserRouter><App/></BrowserRouter></Provider></React.StrictMode>);
